apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-application-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-application
  # Минимально количество реплик установим в 2
  # максимальное, согласно условию - 4
  minReplicas: 2
  maxReplicas: 4
  # Увеличивать количество реплик будем относительно RPS
  # таким образом, в пике (днем) будут активными 4 реплики
  # в часы простоя (ночью) их количество снизится до 2-ух
  metrics:
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: extensions/v1beta1
        kind: Ingress
        name: backend-application-ingress
      target:
        type: Value
        value: 10k